language: cpp

git:
  depth: 1
  
sudo: required

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt; fi

install:
  - mkdir build && cd build

script: 
  - QTVERSION=`ls /usr/local/Cellar/qt`
  - cmake ../sources/ -DQTDIR=/usr/local/Cellar/qt/$QTVERSION/
  - make -j 2

matrix:
    include:
        - os: osx
          osx_image: xcode9.4
